import React, { useState, useMemo } from 'react';
import { Link } from 'react-router-dom';
import { Plus, Minus, Search, ArrowRight } from 'lucide-react';
import Navbar from '../components/Navbar';
import SiteFooter from '../components/SiteFooter';
import { Button } from '@/components/ui/button';

// ── FAQ Data ───────────────────────────────────────────────────────────────────
const FAQ_ITEMS = [
  {
    question: 'What is SoulSathiya?',
    answer:
      'SoulSathiya is a relationship intelligence platform designed to help individuals find deeply compatible life partners through structured psychological insights and meaningful matchmaking. Rather than relying only on profiles, we help you understand how and why a relationship may work.',
    category: 'General',
  },
  {
    question: 'How is SoulSathiya different from other matrimony or dating platforms?',
    answer:
      'Traditional platforms focus on volume and visibility. SoulSathiya focuses on compatibility and clarity. We offer transparent matchmaking, a compatibility-first approach, and insight-driven decisions instead of random swiping.',
    category: 'General',
  },
  {
    question: 'Who is SoulSathiya designed for?',
    answer:
      'SoulSathiya is for individuals who are serious about long-term relationships and prefer a thoughtful, insight-driven approach over casual browsing.',
    category: 'General',
  },
  {
    question: 'How does the matching process work?',
    answer:
      'Matches are generated by evaluating personality traits, emotional tendencies, relationship expectations, and core values. Each match includes a clear explanation of compatibility.',
    category: 'Matching',
  },
  {
    question: 'What does the Compatibility Score mean?',
    answer:
      'The Compatibility Score reflects how well two individuals align across key relationship dimensions such as emotional connection, communication style, and long-term goals.',
    category: 'Matching',
  },
  {
    question: 'Are the profiles shown genuine and relevant?',
    answer:
      'Yes. We prioritise quality over quantity. Profiles are based on compatibility, filtered for activity, and regularly reviewed to minimise inactive or low-quality accounts.',
    category: 'Matching',
  },
  {
    question: 'Is SoulSathiya free to use?',
    answer:
      'Yes. You can create your profile, take the assessment, and explore matches. Optional paid features unlock deeper insights.',
    category: 'Pricing',
  },
  {
    question: 'What does the ₹999 payment include?',
    answer:
      'It unlocks a detailed compatibility report including relationship strengths, challenges, communication patterns, and long-term alignment.',
    category: 'Pricing',
  },
  {
    question: 'Do both people need to pay to connect?',
    answer: 'No. SoulSathiya does not restrict connections through dual-paywalls.',
    category: 'Pricing',
  },
  {
    question: 'Are there any hidden charges or subscriptions?',
    answer: 'No. There are no hidden fees, forced subscriptions, or surprise payments.',
    category: 'Pricing',
  },
  {
    question: 'How do you ensure profile authenticity?',
    answer:
      'We use verification systems, activity tracking, and periodic clean-up of inactive profiles.',
    category: 'Trust & Safety',
  },
  {
    question: 'Will my profile visibility change after payment?',
    answer: 'No. Visibility is based on compatibility, activity, and intent—not payment.',
    category: 'Trust & Safety',
  },
  {
    question: 'Will I know if a user is active?',
    answer: 'Yes. We show activity indicators so you interact with genuine users.',
    category: 'Trust & Safety',
  },
  {
    question: "Why don't you show unlimited profiles?",
    answer: 'We prioritise curated, high-quality matches over overwhelming quantity.',
    category: 'Matching',
  },
  {
    question: "What if I don't get responses?",
    answer:
      'Responses depend on mutual interest, but we ensure your profile is shown to relevant matches.',
    category: 'Matching',
  },
  {
    question: 'Is my data safe?',
    answer: 'Yes. Your data is secure, confidential, and never sold.',
    category: 'Trust & Safety',
  },
  {
    question: "What is SoulSathiya's mission?",
    answer:
      'To increase the number of happy, fulfilling, and lasting marriages through compatibility-driven matchmaking.',
    category: 'General',
  },
  {
    question: 'Why should I trust SoulSathiya?',
    answer: 'Because we grow when you find the right partner—not when you stay searching.',
    category: 'General',
  },
];

// ── Accordion Item ─────────────────────────────────────────────────────────────
function AccordionItem({ item, isOpen, onToggle, index }) {
  return (
    <div
      className={`border-b border-border/40 transition-colors duration-200 ${
        isOpen ? 'bg-white/[0.02]' : 'hover:bg-white/[0.015]'
      }`}
      style={{ animationDelay: `${index * 30}ms` }}
    >
      <button
        onClick={onToggle}
        className="w-full flex items-center justify-between gap-4 py-5 px-1 text-left group"
        aria-expanded={isOpen}
      >
        <span
          className={`text-base font-medium leading-snug transition-colors duration-200 ${
            isOpen ? 'text-primary' : 'text-foreground group-hover:text-primary/80'
          }`}
        >
          {item.question}
        </span>
        <span
          className={`flex-shrink-0 w-7 h-7 rounded-full border flex items-center justify-center transition-all duration-200 ${
            isOpen
              ? 'bg-primary border-primary text-background'
              : 'border-border/60 text-muted-foreground group-hover:border-primary/50 group-hover:text-primary'
          }`}
        >
          {isOpen ? <Minus className="w-3.5 h-3.5" /> : <Plus className="w-3.5 h-3.5" />}
        </span>
      </button>

      {/* Smooth expand / collapse */}
      <div
        style={{
          maxHeight: isOpen ? '500px' : '0px',
          overflow: 'hidden',
          transition: 'max-height 0.35s cubic-bezier(0.4, 0, 0.2, 1)',
        }}
      >
        <p className="text-muted-foreground leading-relaxed text-sm pb-5 px-1 pr-10">
          {item.answer}
        </p>
      </div>
    </div>
  );
}

// ── FAQ Page ───────────────────────────────────────────────────────────────────
export default function FAQPage() {
  const [openIndex, setOpenIndex] = useState(null);
  const [query,     setQuery]     = useState('');

  const filtered = useMemo(() => {
    if (!query.trim()) return FAQ_ITEMS;
    const q = query.toLowerCase();
    return FAQ_ITEMS.filter(
      item =>
        item.question.toLowerCase().includes(q) ||
        item.answer.toLowerCase().includes(q),
    );
  }, [query]);

  const toggle = idx => setOpenIndex(prev => (prev === idx ? null : idx));

  return (
    <div className="min-h-screen bg-background text-foreground flex flex-col">
      <Navbar />

      <main className="flex-1">

        {/* ── Hero ──────────────────────────────────────────────────── */}
        <section className="relative pt-20 pb-14 px-6 overflow-hidden">
          {/* Subtle glow */}
          <div
            className="pointer-events-none absolute -top-32 left-1/2 -translate-x-1/2 w-[600px] h-[400px] rounded-full opacity-10"
            style={{ background: 'radial-gradient(ellipse, #D4A520 0%, transparent 70%)' }}
          />

          <div className="relative max-w-2xl mx-auto text-center">
            <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full border border-primary/30 bg-primary/5 text-primary text-xs font-medium tracking-wider uppercase mb-6">
              Support
            </div>
            <h1 className="font-heading text-4xl md:text-5xl font-bold text-foreground mb-4 leading-tight">
              Frequently Asked
              <span className="text-primary"> Questions</span>
            </h1>
            <p className="text-muted-foreground text-lg leading-relaxed">
              Everything you need to know about SoulSathiya
            </p>
          </div>
        </section>

        {/* ── Search ────────────────────────────────────────────────── */}
        <section className="px-6 pb-10">
          <div className="max-w-xl mx-auto">
            <div className="relative">
              <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground pointer-events-none" />
              <input
                type="text"
                placeholder="Search questions…"
                value={query}
                onChange={e => { setQuery(e.target.value); setOpenIndex(null); }}
                className="w-full pl-11 pr-4 py-3 rounded-xl bg-white/5 border border-border/50 text-foreground placeholder:text-muted-foreground/60 text-sm focus:outline-none focus:border-primary/50 focus:bg-white/[0.07] transition-all duration-200"
              />
              {query && (
                <button
                  onClick={() => { setQuery(''); setOpenIndex(null); }}
                  className="absolute right-4 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground text-xs transition-colors"
                >
                  Clear
                </button>
              )}
            </div>
            {query && (
              <p className="text-xs text-muted-foreground mt-2 ml-1">
                {filtered.length === 0
                  ? 'No results found.'
                  : `${filtered.length} result${filtered.length !== 1 ? 's' : ''} for "${query}"`}
              </p>
            )}
          </div>
        </section>

        {/* ── Accordion ─────────────────────────────────────────────── */}
        <section className="px-6 pb-20">
          <div className="max-w-3xl mx-auto">
            {filtered.length === 0 ? (
              <div className="text-center py-16">
                <p className="text-muted-foreground text-lg mb-2">No matching questions found.</p>
                <p className="text-muted-foreground/60 text-sm">
                  Try a different search term or{' '}
                  <Link to="/contact" className="text-primary hover:underline">
                    contact us
                  </Link>{' '}
                  directly.
                </p>
              </div>
            ) : (
              <div className="rounded-2xl border border-border/40 bg-card/40 px-6 divide-y-0">
                {filtered.map((item, idx) => (
                  <AccordionItem
                    key={item.question}
                    item={item}
                    index={idx}
                    isOpen={openIndex === idx}
                    onToggle={() => toggle(idx)}
                  />
                ))}
              </div>
            )}
          </div>
        </section>

        {/* ── CTA Banner ────────────────────────────────────────────── */}
        <section className="px-6 pb-20">
          <div className="max-w-3xl mx-auto">
            <div className="rounded-2xl border border-primary/20 bg-primary/5 px-8 py-10 text-center">
              <h2 className="font-heading text-2xl font-bold text-foreground mb-2">
                Still have questions?
              </h2>
              <p className="text-muted-foreground text-sm mb-6 leading-relaxed">
                Our team is happy to help. Reach out and we'll get back to you within 24 hours.
              </p>
              <div className="flex flex-col sm:flex-row items-center justify-center gap-3">
                <Link to="/contact">
                  <Button className="btn-primary px-6 font-semibold">
                    Contact Us
                    <ArrowRight className="w-4 h-4 ml-1.5" />
                  </Button>
                </Link>
                <Link to="/register">
                  <Button variant="ghost" className="text-muted-foreground hover:text-foreground hover:bg-white/5 font-medium">
                    Get Started Free
                  </Button>
                </Link>
              </div>
            </div>
          </div>
        </section>

      </main>

      <SiteFooter />
    </div>
  );
}
